wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1670485399.671174
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 55
      3:
      - 5
      - 23
      - 35
      4: 3.9.13
      5: 0.13.6
      8:
      - 5
